name: nf-core-hlatyping-1.1.0
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - fastqc=0.11.7
  - multiqc=1.5
  - optitype=1.3.2
  - yara=0.9.6
  - samtools=1.8
  - conda-forge::coincbc=2.9.9
