name: nf-core-hlatyping-1.1.1
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - fastqc=0.11.8
  - multiqc=1.6
  - optitype=1.3.2
  - yara=1.0.2
  - samtools=1.9
  - conda-forge::coincbc=2.9.9
